#pragma once

#define SOFTWARE_VERSION_MAJOR 2
#define SOFTWARE_VERSION_MINOR 0
#define SOFTWARE_VERSION_BUGFIX 0

#define FIRST_LAUNCH_SETTINGS_OVERRIDE false
#define IS_OTA_FUNCTIONALITY_ENABLED false
#define IS_SYSTEM_RUHESTROMSICHER true

#define TASK_PRIO_HIGH 20
#define TASK_PRIO_MEDIUM 10
#define TASK_PRIO_LOW 2

#define CAN_CORE 1 
#define CAN_TASK_PRIO TASK_PRIO_HIGH

#define SHIFT_LIGHT_CORE 0
#define SHIFT_LIGHT_TASK_PRIO TASK_PRIO_HIGH

#define BLUETOOTH_CORE 1
#define BLUETOOTH_TASK_PRIO TASK_PRIO_MEDIUM

#define WIFI_CONFIG_WEBSITE_CORE 0
#define WIFI_CONFIG_WEBSITE_TASK_PRIO TASK_PRIO_MEDIUM

#define EEPROM_STORAGE_SIZE 6

#define EEPROM_SHIFTLIGHT_ACTIVE_BYTE 0
#define EEPROM_SHIFTLIGHT_BRIGHTNESS_BYTE 1
#define EEPROM_INFO_DISPLAY_MODE_BYTE 2

#define CAN_RX_QUEUE_SIZE 64